seleccionar las métricas por posición para los .py Equipo Propio y 
Buscar Jugadoras. 

Generar diccionario para usuario para las métricas: Equipo Propio.py en 
línea 229.

Crear Reemplazar Jugadora.py con clusterización.